{{- if .Values.autoscaling.enable -}}
{{- $fullName := include "microservice-chart.fullname" . -}}
{{- $triggerAuthentications := .Values.autoscaling.triggerAuthentications | default (list) -}}
{{- $defaultAuthenticationRefName := $fullName -}}
{{- if gt (len $triggerAuthentications) 0 -}}
  {{- $defaultAuthenticationRefName = "" -}}
  {{- if eq (len $triggerAuthentications) 1 -}}
    {{- $defaultAuthenticationRefName = required "autoscaling.triggerAuthentications[0].name is required" (index $triggerAuthentications 0).name -}}
  {{- end -}}
  {{- range $triggerAuthentications }}
{{- $triggerAuthenticationSpec := omit . "name" "workloadIdentity" }}
{{- with .workloadIdentity }}
{{- $_ := set $triggerAuthenticationSpec "podIdentity" . }}
{{- end }}
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: {{ required "autoscaling.triggerAuthentications[].name is required" .name }}
  namespace: {{ $.Values.namespace }}
  labels:
{{ include "microservice-chart.labels" $ | indent 4 }}
spec:
{{ $triggerAuthenticationSpec | toYaml | indent 2 }}
---
  {{- end }}
{{- else }}
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: {{ $fullName }}
  namespace: {{ .Values.namespace }}
spec:
  podIdentity:
    provider: azure-workload
    {{- with .Values.azure.workloadIdentityClientId }}
    identityId: {{ . }}
    {{- end }}
---
{{- end }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ $fullName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "microservice-chart.labels" . | nindent 3 }}
spec:
  scaleTargetRef:
    name: {{ $fullName }}
  minReplicaCount: {{ .Values.autoscaling.minReplica }}
  maxReplicaCount: {{ .Values.autoscaling.maxReplica }}
  pollingInterval: {{ .Values.autoscaling.pollingInterval }}
  cooldownPeriod: {{ .Values.autoscaling.cooldownPeriod }}
  triggers:
    {{- range .Values.autoscaling.triggers }}
    {{- $authenticationRef := .authenticationRef }}
    - type: {{ .type }}
      {{- with .metricType }}
      metricType: {{ . }}
      {{- end }}
      {{- if or $authenticationRef $defaultAuthenticationRefName }}
      authenticationRef:
        {{- if $authenticationRef }}
{{ toYaml $authenticationRef | indent 8 }}
        {{- else }}
        name: {{ $defaultAuthenticationRefName }}
        {{- end }}
      {{- end }}
      metadata:
{{ toYaml .metadata | indent 8 }}
    {{- end }}
  {{- if .Values.autoscaling.advanced }}
  advanced:
    {{- if .Values.autoscaling.advanced.restoreToOriginalReplicaCount }}
    restoreToOriginalReplicaCount: {{ .Values.autoscaling.advanced.restoreToOriginalReplicaCount }}
    {{- end }}
    {{- if .Values.autoscaling.advanced.horizontalPodAutoscalerConfig }}
    horizontalPodAutoscalerConfig:
      #name: keda-hpa-{{ include "microservice-chart.fullname" $ }}
      behavior:
        {{- .Values.autoscaling.advanced.horizontalPodAutoscalerConfig.behavior | toYaml | nindent 8 }}
    {{- end }}
  {{- end }}
{{- end }}
