{{- if or (and .Values.canaryDelivery.create .Values.canaryDelivery.deployment.envConfig) (and .Values.canaryDelivery.create .Values.canaryDelivery.deployment.fileConfig) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "microservice-chart.fullnameCanaryDelivery" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "microservice-chart.labelsCanaryDelivery" . | nindent 4 }}
data:
  {{- if .Values.canaryDelivery.deployment.envConfig -}}
  {{- toYaml .Values.canaryDelivery.deployment.envConfig | nindent 2 }}
  {{- end }}
  {{- if .Values.canaryDelivery.deployment.fileConfig -}}
  {{- toYaml .Values.canaryDelivery.deployment.fileConfig | nindent 2 }}
  {{- end }}
{{- end }}
