{{- if and .Values.canaryDelivery.create .Values.canaryDelivery.serviceMonitor.create -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "microservice-chart.fullnameCanaryDelivery" . }}
  namespace: {{ .Values.namespace }}
  labels:
    release: prometheus
    {{- include "microservice-chart.labelsCanaryDelivery" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "microservice-chart.labelsCanaryDelivery" . | nindent 6 }}
  endpoints:
    {{- range  $k, $v := .Values.canaryDelivery.serviceMonitor.endpoints }}
    - interval: {{ $v.interval }}
      targetPort: {{ $v.targetPort }}
      path: {{ $v.path }}
    {{- end }}
{{- end }}

---
