{{- if and .Values.canaryDelivery.create .Values.canaryDelivery.service.create -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "microservice-chart.fullnameCanaryDelivery" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "microservice-chart.labelsCanaryDelivery" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - name: beta-app-port-{{ . }}-svc
      port: {{ . }}
      targetPort: {{ . }}
      protocol: TCP
    {{- end }}
  selector:
    {{- include "microservice-chart.selectorLabelsCanaryDelivery" . | nindent 4 }}
{{- end }}

