{{- if and .Values.canaryDelivery.create .Values.canaryDelivery.deployment.envConfig -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "microservice-chart.fullnamecanaryDelivery" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "microservice-chart.labelscanaryDelivery" . | nindent 4 }}
data:
  {{- toYaml .Values.canaryDelivery.deployment.envConfig | nindent 2 }}
{{- end }}
