{{- if .Values.envSecret -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "microservice-chart.fullname" . }}
  labels:
    {{- include "microservice-chart.labels" . | nindent 4 }}
spec:
  provider: azure
  secretObjects:
    {{- range $key, $objectName := .Values.envSecret }}
    - secretName: {{ include "microservice-chart.fullname" $ }}
      type: Opaque
      data:
      - key: {{ $objectName }}
        objectName: {{ $objectName }}
    {{- end }}
  parameters:
    usePodIdentity: "true"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: ""
    keyvaultName: {{ .Values.keyvault.name }}
    tenantId: {{ .Values.keyvault.tenantId }}
    cloudName: ""
    objects: |
      array:
        {{- range $key, $objectName := .Values.envSecret }}
        - |
          objectName: {{ $objectName }}
          objectType: secret
          objectVersion: ""
        {{- end }}
{{- end }}
