{{- if .Values.service.create -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "microservice-chart.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "microservice-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - name: app-port-{{ . }}-svc
      port: {{ . }}
      targetPort: {{ . }}
      protocol: TCP
    {{- end }}
  selector:
    {{- include "microservice-chart.selectorLabels" . | nindent 4 }}
{{- end }}
