{{- if .Values.service.create -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "microservice-chart.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "microservice-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: app-port-{{ .Values.service.port }}
  selector:
    {{- include "microservice-chart.selectorLabels" . | nindent 4 }}
{{- end }}
