---
apiVersion: v1
kind: Service
metadata:
  labels:
    prometheus: "true"
  name: pdnd-interop-uservice-user-registry-management
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 8088
      targetPort: http
      protocol: TCP
      name: http
    - port: 9095
      targetPort: monitoring
      protocol: TCP
      name: monitoring
  selector:
    app: pdnd-interop-uservice-user-registry-management
