apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "microservice-chart.fullname" . }}
  labels:
    {{- include "microservice-chart.labels" . | nindent 4 }}
data:
  {{ toYaml .Values.envConfig }}

