apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: {{ include "microservice-chart.fullname" . }}
spec:
  podIdentity:
    provider: azure
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "microservice-chart.fullname" . }}
  labels:
    {{- include "microservice-chart.labels" . | nindent 3 }}
spec:
  scaleTargetRef:
    name: {{ include "microservice-chart.fullname" . }}
  minReplicaCount: {{ .Values.autoscaling.minReplica }}
  maxReplicaCount: {{ .Values.autoscaling.maxReplica }}
  pollingInterval: {{ .Values.autoscaling.pollingInterval }}
  cooldownPeriod: {{ .Values.autoscaling.cooldownPeriod }}
  triggers:
    {{- range .Values.autoscaling.triggers }}
    - type: {{ .type }}
      authenticationRef:
        name: {{ include "microservice-chart.fullname" $ }}
      metadata:
        {{- .metadata | toYaml | nindent 8 }}
    {{- end }}
