apiVersion: v1
kind: Secret
metadata:
  name: {{ include "microservice-chart.fullname" . }}
  labels:
    {{- include "microservice-chart.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.envSecret }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end }}
