apiVersion: v2
name: progressive-delivery
description: An example application with Java spring boot
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
- name: microservice-chart
  version: 1.19.0
  repository: file://../../../charts/microservice-chart
