apiVersion: v2
name: test-aks-microservice-chart-blueprint
description: An example application with Java spring boot
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
- name: microservice-chart
  version: 1.13.0
  repository: file://../../../charts/microservice-chart
