microservice-chart:
  namespace: "idpay"
  nameOverride: ""
  fullnameOverride: ""

  image:
    repository: ghcr.io/pagopa/devops-springboot-gitlab-workflow
    tag: 0.4.0
    pullPolicy: Always

  deployment:
    create: true

  service:
    create: true
    type: ClusterIP
    port: 8080

  ingress:
    create: true
    host: "dev01.idpay.internal.dev.cstar.pagopa.it"
    path: /idpay/test/(.*)

  serviceAccount:
    create: false
    annotations: {}
    name: ""

  podAnnotations: {}

  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault

  securityContext:
    allowPrivilegeEscalation: false

  resources:
    requests:
      memory: "96Mi"
      cpu: "40m"
    limits:
      memory: "128Mi"
      cpu: "150m"

  autoscaling:
    minReplica: 1
    maxReplica: 2
    pollingInterval: 30 # seconds
    cooldownPeriod: 300 # seconds
    triggers:
      - type: azure-monitor
        metadata:
          tenantId: 7788edaf-0346-4068-9d79-c868aed15b3d
          subscriptionId: ac17914c-79bf-48fa-831e-1359ef74c1d5
          resourceGroupName: dvopla-d-sec-rg
          resourceURI: Microsoft.KeyVault/vaults/dvopla-d-neu-kv
          metricName: ServiceApiHit
          # metricNamespace: Microsoft.KeyVault/vaults
          # metricFilter: namespace eq 'default'
          # metricAggregationInterval: "-1:1:0"
          metricAggregationType: Count
          targetValue: "30"

  # envConfig:
  #   USER: my-user

  # envSecret:
  #   PASS: helm-template-password

  keyvault:
    name: "cstar-d-idpay-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"

  # nodeSelector: {}

  # tolerations: []

  # affinity: {}
