image:
  repository: dvopladneuacr.azurecr.io/templatemicroserviziok8s
  tag: "1dd0109082e799bd5ee4474de2433a91d2b95fc5"
  pullPolicy: Always

livenessProbe:
  httpGet:
    path: /healthz/live
    port: 8080
  initialDelaySeconds: 60
  failureThreshold: 6
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /healthz/ready
    port: 8080
  initialDelaySeconds: 60
  failureThreshold: 6
  periodSeconds: 10

namespace: "helm-template"
nameOverride: ""
fullnameOverride: ""

deployment:
  create: true

ingress:
  create: true
  host: "helm-template.ingress.devopslab.pagopa.it"
  path: /idpay/test/(.*)

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    memory: "96Mi"
    cpu: "40m"
  limits:
    memory: "128Mi"
    cpu: "150m"

autoscaling:
  enable: true
  minReplica: 1
  maxReplica: 2
  pollingInterval: 30 # seconds
  cooldownPeriod: 300 # seconds
  triggers:
    - type: azure-monitor
      metadata:
        tenantId: 7788edaf-0346-4068-9d79-c868aed15b3d
        subscriptionId: ac17914c-79bf-48fa-831e-1359ef74c1d5
        resourceGroupName: dvopla-d-sec-rg
        resourceURI: Microsoft.KeyVault/vaults/dvopla-d-neu-kv
        metricName: ServiceApiHit
        # metricNamespace: Microsoft.KeyVault/vaults
        # metricFilter: namespace eq 'default'
        # metricAggregationInterval: "-1:1:0"
        metricAggregationType: Count
        targetValue: "30"

envConfig:
  USER: my-user

envSecret:
  PASS: helm-template-password

keyvault:
  name: "dvopla-d-neu-kv"
  tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"

nodeSelector: {}

tolerations: []

affinity: {}

