microservice-chart:
  namespace: "idpay"
  nameOverride: ""
  fullnameOverride: ""

  image:
    repository: ghcr.io/pagopa/devops-java-springboot-color
    tag: 0.6.0
    pullPolicy: Always

  livenessProbe:
    httpGet:
      path: /status/live
      port: 8080
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10

  readinessProbe:
    httpGet:
      path: /status/ready
      port: 8080
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10

  deployment:
    create: true

  service:
    create: true
    type: ClusterIP
    port: 8080

  ingress:
    create: true
    host: "dev01.idpay.internal.dev.cstar.pagopa.it"
    path: /idpay/testbar/(.*)

  serviceAccount:
    create: false
    annotations: {}
    name: ""

  podAnnotations: {}

  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault

  securityContext:
    allowPrivilegeEscalation: false

  resources:
    requests:
      memory: "256Mi"
      cpu: "40m"
    limits:
      memory: "256Mi"
      cpu: "150m"

  autoscaling:
    enable: true
    minReplica: 1
    maxReplica: 2
    pollingInterval: 30 # seconds
    cooldownPeriod: 300 # seconds
    triggers:
      - type: azure-monitor
        metadata:
          tenantId: 7788edaf-0346-4068-9d79-c868aed15b3d
          subscriptionId: ac17914c-79bf-48fa-831e-1359ef74c1d5
          resourceGroupName: dvopla-d-sec-rg
          resourceURI: Microsoft.KeyVault/vaults/dvopla-d-neu-kv
          metricName: ServiceApiHit
          # metricNamespace: Microsoft.KeyVault/vaults
          # metricFilter: namespace eq 'default'
          # metricAggregationInterval: "-1:1:0"
          metricAggregationType: Count
          targetValue: "30"

  envConfig:
    APP: foo

  envSecret:
    aks-api-url: cstar-d-weu-dev01-aks-apiserver-url

  keyvault:
    name: "cstar-d-idpay-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"

  # nodeSelector: {}

  # tolerations: []

  # affinity: {}
