microservice-chart:
  namespace: ""
  nameOverride: ""
  fullnameOverride: ""

  image:
    repository: ""
    pullPolicy: Always
    tag: "1.0.0"

  ingress:
    host: ""

  serviceAccount:
    create: false
    annotations: {}
    name: ""

  podAnnotations: {}

  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault

  securityContext:
    allowPrivilegeEscalation: false

  service:
    type: ClusterIP
    port: 80

  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "128Mi"
      cpu: "500m"

  autoscaling:
    minReplica: 1
    maxReplica: 1
    pollingInterval: 30 # seconds
    cooldownPeriod: 300 # seconds
    triggers: []

  envConfig: {}

  envSecret: {}

  keyvault:
    name: ""
    tenantId: ""

  nodeSelector: {}

  tolerations: []

  affinity: {}
