image:
  repository: ""
  tag: "v1.0.0"
  pullPolicy: Always

namespace: ""
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    memory: "96Mi"
    cpu: "40m"
  limits:
    memory: "128Mi"
    cpu: "150m"

autoscaling:
  minReplica: 1
  maxReplica: 1
  pollingInterval: 30 # seconds
  cooldownPeriod: 300 # seconds
  triggers: []

envConfig: {}

envSecret: {}

keyvault:
  name: ""
  tenantId: ""

nodeSelector: {}

tolerations: []

affinity: {}

