microservice-chart:
  namespace: "diego"
  nameOverride: ""
  fullnameOverride: ""

  canaryDelivery:
    create: false
    ingress:
      create: true
      canary:
        type: bluegreen
      # canary:
      #   type: header
      #   headerName: canary
      #   headerValue: pagopa
      #   weightPercent: 10
    service:
      create: true
    deployment:
      create: true
      image:
        repository: ghcr.io/pagopa/devops-java-springboot-color
        tag: 0.8.1
        pullPolicy: Always
      envConfig:
        MY_APP_COLOR: "blue"
        progressive-delivery: "ok"
      envSecret:
        aks-api-url: dvopla-d-neu-dev01-aks-apiserver-url

  deployment:
    create: true
    replicas: 4

  envConfig:
    APP: foo
    MY_APP_COLOR: "green"

  envSecret:
    aks-api-url: dvopla-d-neu-dev01-aks-apiserver-url

  image:
    repository: ghcr.io/pagopa/devops-java-springboot-color
    tag: 0.8.1
    pullPolicy: Always

  livenessProbe:
    httpGet:
      path: /status/live
      port: 8080
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10

  readinessProbe:
    httpGet:
      path: /status/ready
      port: 8080
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10

  service:
    create: true
    type: ClusterIP
    ports:
      - 8080

  ingress:
    create: false
    host: ""
    path: /diego/color(/|$)(.*)
    rewriteTarget: /$2
    servicePort: 8080

  serviceAccount:
    create: false
    annotations: {}
    name: ""

  podAnnotations: {}

  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault

  securityContext:
    allowPrivilegeEscalation: false

  resources:
    requests:
      memory: "256Mi"
      cpu: "40m"
    limits:
      memory: "256Mi"
      cpu: "150m"

  autoscaling:
    enable: false
    minReplica: 1
    maxReplica: 2
    pollingInterval: 30 # seconds
    cooldownPeriod: 300 # seconds
    triggers:
      - type: azure-monitor
        metadata:
          tenantId: 7788edaf-0346-4068-9d79-c868aed15b3d
          subscriptionId: ac17914c-79bf-48fa-831e-1359ef74c1d5
          resourceGroupName: dvopla-d-sec-rg
          resourceURI: Microsoft.KeyVault/vaults/dvopla-d-neu-kv
          metricName: ServiceApiHit
          # metricNamespace: Microsoft.KeyVault/vaults
          # metricFilter: namespace eq 'default'
          # metricAggregationInterval: "-1:1:0"
          metricAggregationType: Count
          targetValue: "30"

  keyvault:
    name: "dvopla-d-diego-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"

  # nodeSelector: {}

  # tolerations: []

  # affinity: {}
