name: check_helm

on:
  push:

jobs:
  check_helm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: setup_python
        uses: actions/setup-python@v2

      - name: setup_pip
        run: |
          python -m ensurepip --upgrade

      - name: setup_checkcov
        run: |
          python -m pip install -U checkov

      - name: setup_helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh

      - name: run_checkov_dev
        run: |
          FILE=./helm/values-dev.yaml
          if [ -f "$FILE" ]; then
            checkov -d ./helm --framework helm --var-file "$FILE"
          else
            echo "$FILE does not exist."
            exit 0
          fi

      - name: run_checkov_uat
        run: |
          FILE=./helm/values-uat.yaml
          if [ -f "$FILE" ]; then
            checkov -d ./helm --framework helm --var-file "$FILE"
          else
            echo "$FILE does not exist."
            exit 0
          fi

      - name: run_checkov_prod
        run: |
          FILE=./helm/values-prod.yaml
          if [ -f "$FILE" ]; then
            checkov -d ./helm --framework helm --var-file "$FILE"
          else
            echo "$FILE does not exist."
            exit 0
          fi
