name: check_helm

on:
  push:

jobs:
  check_helm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: setup_python
        uses: actions/setup-python@v2

      - name: setup_pip
        run: |
          python -m ensurepip --upgrade

      - name: setup_checkcov
        run: |
          python -m pip install -U checkov

      - name: setup_helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh

      - name: run_checkov_local
        run: |
          [ -f ./helm/values_local.yaml ] && checkov -d ./helm --framework helm --var-file ./helm/values_local.yaml

      - name: run_checkov_dev
        run: |
          [ -f ./helm/values_dev.yaml ] && checkov -d ./helm --framework helm --var-file ./helm/values_dev.yaml

      - name: run_checkov_uat
        run: |
          [ -f ./helm/values_uat.yaml ] && checkov -d ./helm --framework helm --var-file ./helm/values_uat.yaml

      - name: run_checkov_prod
        run: |
          [ -f ./helm/values_prod.yaml ] && checkov -d ./helm --framework helm --var-file ./helm/values_prod.yaml
